version: '3.8'

name: wholesaler-app
services:
  database-mysql:
    image: mysql:9.0.1
    container_name: database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wholesaler
      MYSQL_USER: test
      MYSQL_PASSWORD: test
#    volumes:
#        - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
#        - ./src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    ports:
      - "3306:3306"
  wholesaler-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-mysql:3306/wholesaler
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
