#app:
#  db-init: false
logging:
  level:
    org:
      springframework:
        web: TRACE
spring:
  sql:
    init:
      mode: always
  datasource:
#    url: jdbc:mysql://localhost:3306/wholesaler?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/wholesaler
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show:
          sql: true
    show-sql: true
    defer-datasource-initialization: true
#    generate-ddl: true

#---
#spring:
#  config:
#    activate:
#      on-profile: test
##rsa.private-key=classpath:certs/private.pem
##rsa.public-key=classpath:certs/public.pem
#
##spring.security.user.password=123
#
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.show-sql: true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:mysql://localhost:3306/wholesaler?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.properties.hibernates.show.sql=true
#logging.level.org.springframework.web=TRACE
#app.db-init=false